name: Build Site Develop

on:
  push:
    branches:
      - develop

jobs:
  build-develop:
    
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Setup dart-sass-embedded
      run: |
        curl -s https://api.github.com/repos/sass/dart-sass-embedded/releases/latest \
        | grep "browser_download_url.*linux-x64" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | xargs wget -qO- \
        | tar xvz -C /tmp
        chmod 755 /tmp/sass_embedded/dart-sass-embedded
        ln -s /tmp/sass_embedded/dart-sass-embedded /usr/local/bin

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Install dependencies
      run: npm ci

    - name: Build site
      run: npm run build:site
